#info
title: awolfe76
desc: Designing, organizing, architecting and building on the web for the past 13 years.
sub-desc: I write posts that are 500 words or less. Simple and quick to read (2 minute and 30 seconds or less).
disclaimer: Content on this site is my own and in no way represents my employer at anytime. Some of the work, however, is work done for my employer(s).

name: Andrew Wolfe
email: awolfe76@gmail.com
dribbble: http://dribbble.com/awolfe76
github: https://github.com/awolfe76
twitter: https://twitter.com/awolfe76

#build config
markdown: rdiscount
